run-name: Deploy


on: 
  workflow_dispatch:




jobs:
  greeting:
    uses: thejitenderk/reusable-workflow/.github/workflows/practice.yml@main
    with:
      environment: prod
      image_name: ubuntu-latest
      stepname: architkapipeline
      



